### ISSUE TITLE
This addon no longer works

### ISSUE THREAD

**Issue by jakesgh** [VeryBaddude/plugin.video.curiositystream#8]
When you install the addon on the latest Kodi, it doesn't open.

**Comment by ireeus** [comment]
kodi.log:
2019-05-11 15:16:19.332 T:1456   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'alt-1-science'
                                            Traceback (most recent call last):
                                              File "C:\Users\nicole\AppData\Roaming\Kodi\addons\plugin.video.curiositystream\addon.py", line 356, in <module>
                                                list_categories(token)
                                              File "C:\Users\nicole\AppData\Roaming\Kodi\addons\plugin.video.curiositystream\addon.py", line 156, in list_categories
                                                debug('Setting art to ' + cat[group['name']]['image'])
                                            KeyError: u'alt-1-science'
                                            -->End of Python script error report<--
2019-05-11 15:16:19.348 T:4252   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.curiositystream/
2019-05-11 15:16:19.363 T:6508   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.curiositystream/) failed

**Comment by jakesgh** [comment]
Thought I posted my log. But this ⬆️

**Comment by AncaTodirica** [comment]
Created pr that fixes the issue https://github.com/VeryBaddude/plugin.video.curiositystream/pull/9

**Comment by matthuisman** [comment]
Try my new add-on if you like
https://www.matthuisman.nz/2019/07/curiositystream-kodi-add-on.html
